### ISSUE TITLE
甲骨文使用脚本出错

### ISSUE THREAD

**Issue by stationofldyc** [YG-tsj/oneclickroot#1]
开的新机器
/dev/fd/63: line 1: Failed: command not found

**Comment by YG-tsj** [comment]
bash <(curl -sSL https://cdn.jsdelivr.net/gh/YG-tsj/oneclickroot/root.sh)

**Comment by YG-tsj** [comment]
> 开的新机器
> /dev/fd/63: line 1: Failed: command not found

哈哈，脚本少打了一个o。。。已修正
